name: LoopPlugin
main: Hax.Bukkit.LoopPlugin.LoopPlugin
version: 1.0
commands:
  loop:
    description: Execute other commands in a loop!
    usage: /loop command repeatTimes delay
    permission: LoopPlugin.loop
    permission-message: You don't have permission. Try sudo :)